//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerClient_WebApplication.OrderServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderServiceReference.OrderWebServiceSoap")]
    public interface OrderWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoOrderId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AutoOrderId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoOrderId", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AutoOrderIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchProdcut", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SearchProdcut(string productname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchProdcut", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SearchProdcutAsync(string productname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getProductName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getProductName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getProductName", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getProductNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getProductId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getProductId(string ProductName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getProductId", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getProductIdAsync(string ProductName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertOrder(string orderId, string customer, string flowerId, int qty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsertOrderAsync(string orderId, string customer, string flowerId, int qty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DisplayOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DisplayOrder();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DisplayOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> DisplayOrderAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateOrder(string OrderId, string ProductId, int Qty, string customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdateOrderAsync(string OrderId, string ProductId, int Qty, string customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DeleteOrder(string OrderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DeleteOrderAsync(string OrderId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrderWebServiceSoapChannel : CustomerClient_WebApplication.OrderServiceReference.OrderWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderWebServiceSoapClient : System.ServiceModel.ClientBase<CustomerClient_WebApplication.OrderServiceReference.OrderWebServiceSoap>, CustomerClient_WebApplication.OrderServiceReference.OrderWebServiceSoap {
        
        public OrderWebServiceSoapClient() {
        }
        
        public OrderWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AutoOrderId() {
            return base.Channel.AutoOrderId();
        }
        
        public System.Threading.Tasks.Task<string> AutoOrderIdAsync() {
            return base.Channel.AutoOrderIdAsync();
        }
        
        public System.Data.DataSet SearchProdcut(string productname) {
            return base.Channel.SearchProdcut(productname);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SearchProdcutAsync(string productname) {
            return base.Channel.SearchProdcutAsync(productname);
        }
        
        public System.Data.DataSet getProductName() {
            return base.Channel.getProductName();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getProductNameAsync() {
            return base.Channel.getProductNameAsync();
        }
        
        public string getProductId(string ProductName) {
            return base.Channel.getProductId(ProductName);
        }
        
        public System.Threading.Tasks.Task<string> getProductIdAsync(string ProductName) {
            return base.Channel.getProductIdAsync(ProductName);
        }
        
        public string InsertOrder(string orderId, string customer, string flowerId, int qty) {
            return base.Channel.InsertOrder(orderId, customer, flowerId, qty);
        }
        
        public System.Threading.Tasks.Task<string> InsertOrderAsync(string orderId, string customer, string flowerId, int qty) {
            return base.Channel.InsertOrderAsync(orderId, customer, flowerId, qty);
        }
        
        public System.Data.DataSet DisplayOrder() {
            return base.Channel.DisplayOrder();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DisplayOrderAsync() {
            return base.Channel.DisplayOrderAsync();
        }
        
        public string UpdateOrder(string OrderId, string ProductId, int Qty, string customer) {
            return base.Channel.UpdateOrder(OrderId, ProductId, Qty, customer);
        }
        
        public System.Threading.Tasks.Task<string> UpdateOrderAsync(string OrderId, string ProductId, int Qty, string customer) {
            return base.Channel.UpdateOrderAsync(OrderId, ProductId, Qty, customer);
        }
        
        public string DeleteOrder(string OrderId) {
            return base.Channel.DeleteOrder(OrderId);
        }
        
        public System.Threading.Tasks.Task<string> DeleteOrderAsync(string OrderId) {
            return base.Channel.DeleteOrderAsync(OrderId);
        }
    }
}
