//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerClient_WebApplication.CustomerServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerServiceReference.CustomerWebServiceSoap")]
    public interface CustomerWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name AutoCustomerIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoCustomerId", ReplyAction="*")]
        CustomerClient_WebApplication.CustomerServiceReference.AutoCustomerIdResponse AutoCustomerId(CustomerClient_WebApplication.CustomerServiceReference.AutoCustomerIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoCustomerId", ReplyAction="*")]
        System.Threading.Tasks.Task<CustomerClient_WebApplication.CustomerServiceReference.AutoCustomerIdResponse> AutoCustomerIdAsync(CustomerClient_WebApplication.CustomerServiceReference.AutoCustomerIdRequest request);
        
        // CODEGEN: Generating message contract since element name CustomerId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertCustomer", ReplyAction="*")]
        CustomerClient_WebApplication.CustomerServiceReference.insertCustomerResponse insertCustomer(CustomerClient_WebApplication.CustomerServiceReference.insertCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<CustomerClient_WebApplication.CustomerServiceReference.insertCustomerResponse> insertCustomerAsync(CustomerClient_WebApplication.CustomerServiceReference.insertCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/loginCustomer", ReplyAction="*")]
        CustomerClient_WebApplication.CustomerServiceReference.loginCustomerResponse loginCustomer(CustomerClient_WebApplication.CustomerServiceReference.loginCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/loginCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<CustomerClient_WebApplication.CustomerServiceReference.loginCustomerResponse> loginCustomerAsync(CustomerClient_WebApplication.CustomerServiceReference.loginCustomerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoCustomerIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoCustomerId", Namespace="http://tempuri.org/", Order=0)]
        public CustomerClient_WebApplication.CustomerServiceReference.AutoCustomerIdRequestBody Body;
        
        public AutoCustomerIdRequest() {
        }
        
        public AutoCustomerIdRequest(CustomerClient_WebApplication.CustomerServiceReference.AutoCustomerIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AutoCustomerIdRequestBody {
        
        public AutoCustomerIdRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoCustomerIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoCustomerIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public CustomerClient_WebApplication.CustomerServiceReference.AutoCustomerIdResponseBody Body;
        
        public AutoCustomerIdResponse() {
        }
        
        public AutoCustomerIdResponse(CustomerClient_WebApplication.CustomerServiceReference.AutoCustomerIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AutoCustomerIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AutoCustomerIdResult;
        
        public AutoCustomerIdResponseBody() {
        }
        
        public AutoCustomerIdResponseBody(string AutoCustomerIdResult) {
            this.AutoCustomerIdResult = AutoCustomerIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertCustomer", Namespace="http://tempuri.org/", Order=0)]
        public CustomerClient_WebApplication.CustomerServiceReference.insertCustomerRequestBody Body;
        
        public insertCustomerRequest() {
        }
        
        public insertCustomerRequest(CustomerClient_WebApplication.CustomerServiceReference.insertCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CustomerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CustomerName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Contact;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Address;
        
        public insertCustomerRequestBody() {
        }
        
        public insertCustomerRequestBody(string CustomerId, string CustomerName, string Password, string Email, string Contact, string Address) {
            this.CustomerId = CustomerId;
            this.CustomerName = CustomerName;
            this.Password = Password;
            this.Email = Email;
            this.Contact = Contact;
            this.Address = Address;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public CustomerClient_WebApplication.CustomerServiceReference.insertCustomerResponseBody Body;
        
        public insertCustomerResponse() {
        }
        
        public insertCustomerResponse(CustomerClient_WebApplication.CustomerServiceReference.insertCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insertCustomerResult;
        
        public insertCustomerResponseBody() {
        }
        
        public insertCustomerResponseBody(string insertCustomerResult) {
            this.insertCustomerResult = insertCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginCustomer", Namespace="http://tempuri.org/", Order=0)]
        public CustomerClient_WebApplication.CustomerServiceReference.loginCustomerRequestBody Body;
        
        public loginCustomerRequest() {
        }
        
        public loginCustomerRequest(CustomerClient_WebApplication.CustomerServiceReference.loginCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public loginCustomerRequestBody() {
        }
        
        public loginCustomerRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public CustomerClient_WebApplication.CustomerServiceReference.loginCustomerResponseBody Body;
        
        public loginCustomerResponse() {
        }
        
        public loginCustomerResponse(CustomerClient_WebApplication.CustomerServiceReference.loginCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginCustomerResult;
        
        public loginCustomerResponseBody() {
        }
        
        public loginCustomerResponseBody(string loginCustomerResult) {
            this.loginCustomerResult = loginCustomerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerWebServiceSoapChannel : CustomerClient_WebApplication.CustomerServiceReference.CustomerWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerWebServiceSoapClient : System.ServiceModel.ClientBase<CustomerClient_WebApplication.CustomerServiceReference.CustomerWebServiceSoap>, CustomerClient_WebApplication.CustomerServiceReference.CustomerWebServiceSoap {
        
        public CustomerWebServiceSoapClient() {
        }
        
        public CustomerWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CustomerClient_WebApplication.CustomerServiceReference.AutoCustomerIdResponse CustomerClient_WebApplication.CustomerServiceReference.CustomerWebServiceSoap.AutoCustomerId(CustomerClient_WebApplication.CustomerServiceReference.AutoCustomerIdRequest request) {
            return base.Channel.AutoCustomerId(request);
        }
        
        public string AutoCustomerId() {
            CustomerClient_WebApplication.CustomerServiceReference.AutoCustomerIdRequest inValue = new CustomerClient_WebApplication.CustomerServiceReference.AutoCustomerIdRequest();
            inValue.Body = new CustomerClient_WebApplication.CustomerServiceReference.AutoCustomerIdRequestBody();
            CustomerClient_WebApplication.CustomerServiceReference.AutoCustomerIdResponse retVal = ((CustomerClient_WebApplication.CustomerServiceReference.CustomerWebServiceSoap)(this)).AutoCustomerId(inValue);
            return retVal.Body.AutoCustomerIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CustomerClient_WebApplication.CustomerServiceReference.AutoCustomerIdResponse> CustomerClient_WebApplication.CustomerServiceReference.CustomerWebServiceSoap.AutoCustomerIdAsync(CustomerClient_WebApplication.CustomerServiceReference.AutoCustomerIdRequest request) {
            return base.Channel.AutoCustomerIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<CustomerClient_WebApplication.CustomerServiceReference.AutoCustomerIdResponse> AutoCustomerIdAsync() {
            CustomerClient_WebApplication.CustomerServiceReference.AutoCustomerIdRequest inValue = new CustomerClient_WebApplication.CustomerServiceReference.AutoCustomerIdRequest();
            inValue.Body = new CustomerClient_WebApplication.CustomerServiceReference.AutoCustomerIdRequestBody();
            return ((CustomerClient_WebApplication.CustomerServiceReference.CustomerWebServiceSoap)(this)).AutoCustomerIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CustomerClient_WebApplication.CustomerServiceReference.insertCustomerResponse CustomerClient_WebApplication.CustomerServiceReference.CustomerWebServiceSoap.insertCustomer(CustomerClient_WebApplication.CustomerServiceReference.insertCustomerRequest request) {
            return base.Channel.insertCustomer(request);
        }
        
        public string insertCustomer(string CustomerId, string CustomerName, string Password, string Email, string Contact, string Address) {
            CustomerClient_WebApplication.CustomerServiceReference.insertCustomerRequest inValue = new CustomerClient_WebApplication.CustomerServiceReference.insertCustomerRequest();
            inValue.Body = new CustomerClient_WebApplication.CustomerServiceReference.insertCustomerRequestBody();
            inValue.Body.CustomerId = CustomerId;
            inValue.Body.CustomerName = CustomerName;
            inValue.Body.Password = Password;
            inValue.Body.Email = Email;
            inValue.Body.Contact = Contact;
            inValue.Body.Address = Address;
            CustomerClient_WebApplication.CustomerServiceReference.insertCustomerResponse retVal = ((CustomerClient_WebApplication.CustomerServiceReference.CustomerWebServiceSoap)(this)).insertCustomer(inValue);
            return retVal.Body.insertCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CustomerClient_WebApplication.CustomerServiceReference.insertCustomerResponse> CustomerClient_WebApplication.CustomerServiceReference.CustomerWebServiceSoap.insertCustomerAsync(CustomerClient_WebApplication.CustomerServiceReference.insertCustomerRequest request) {
            return base.Channel.insertCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<CustomerClient_WebApplication.CustomerServiceReference.insertCustomerResponse> insertCustomerAsync(string CustomerId, string CustomerName, string Password, string Email, string Contact, string Address) {
            CustomerClient_WebApplication.CustomerServiceReference.insertCustomerRequest inValue = new CustomerClient_WebApplication.CustomerServiceReference.insertCustomerRequest();
            inValue.Body = new CustomerClient_WebApplication.CustomerServiceReference.insertCustomerRequestBody();
            inValue.Body.CustomerId = CustomerId;
            inValue.Body.CustomerName = CustomerName;
            inValue.Body.Password = Password;
            inValue.Body.Email = Email;
            inValue.Body.Contact = Contact;
            inValue.Body.Address = Address;
            return ((CustomerClient_WebApplication.CustomerServiceReference.CustomerWebServiceSoap)(this)).insertCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CustomerClient_WebApplication.CustomerServiceReference.loginCustomerResponse CustomerClient_WebApplication.CustomerServiceReference.CustomerWebServiceSoap.loginCustomer(CustomerClient_WebApplication.CustomerServiceReference.loginCustomerRequest request) {
            return base.Channel.loginCustomer(request);
        }
        
        public string loginCustomer(string username, string password) {
            CustomerClient_WebApplication.CustomerServiceReference.loginCustomerRequest inValue = new CustomerClient_WebApplication.CustomerServiceReference.loginCustomerRequest();
            inValue.Body = new CustomerClient_WebApplication.CustomerServiceReference.loginCustomerRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            CustomerClient_WebApplication.CustomerServiceReference.loginCustomerResponse retVal = ((CustomerClient_WebApplication.CustomerServiceReference.CustomerWebServiceSoap)(this)).loginCustomer(inValue);
            return retVal.Body.loginCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CustomerClient_WebApplication.CustomerServiceReference.loginCustomerResponse> CustomerClient_WebApplication.CustomerServiceReference.CustomerWebServiceSoap.loginCustomerAsync(CustomerClient_WebApplication.CustomerServiceReference.loginCustomerRequest request) {
            return base.Channel.loginCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<CustomerClient_WebApplication.CustomerServiceReference.loginCustomerResponse> loginCustomerAsync(string username, string password) {
            CustomerClient_WebApplication.CustomerServiceReference.loginCustomerRequest inValue = new CustomerClient_WebApplication.CustomerServiceReference.loginCustomerRequest();
            inValue.Body = new CustomerClient_WebApplication.CustomerServiceReference.loginCustomerRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((CustomerClient_WebApplication.CustomerServiceReference.CustomerWebServiceSoap)(this)).loginCustomerAsync(inValue);
        }
    }
}
