//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerClient_WebApplication.ProductServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductServiceReference.ProductWebServiceSoap")]
    public interface ProductWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoProdcutId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AutoProdcutId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoProdcutId", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AutoProdcutIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCategoryName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getCategoryName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCategoryName", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getCategoryNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCategoryId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getCategoryId(string categoryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCategoryId", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getCategoryIdAsync(string categoryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string insertProduct(string productId, string ProductName, string categoryId, int price, int qty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<string> insertProductAsync(string productId, string ProductName, string categoryId, int price, int qty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchProdcut", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SearchProdcut(string productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchProdcut", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SearchProdcutAsync(string productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DisplayProduct1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DisplayProduct1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DisplayProduct1", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> DisplayProduct1Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateProduct(string productId1, string ProductName, string categoryId, int price, int qty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdateProductAsync(string productId1, string ProductName, string categoryId, int price, int qty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DeleteProduct(string ProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DeleteProductAsync(string ProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddStock", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int AddStock(string productId, int newStock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddStock", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddStockAsync(string productId, int newStock);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductWebServiceSoapChannel : CustomerClient_WebApplication.ProductServiceReference.ProductWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductWebServiceSoapClient : System.ServiceModel.ClientBase<CustomerClient_WebApplication.ProductServiceReference.ProductWebServiceSoap>, CustomerClient_WebApplication.ProductServiceReference.ProductWebServiceSoap {
        
        public ProductWebServiceSoapClient() {
        }
        
        public ProductWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AutoProdcutId() {
            return base.Channel.AutoProdcutId();
        }
        
        public System.Threading.Tasks.Task<string> AutoProdcutIdAsync() {
            return base.Channel.AutoProdcutIdAsync();
        }
        
        public System.Data.DataSet getCategoryName() {
            return base.Channel.getCategoryName();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getCategoryNameAsync() {
            return base.Channel.getCategoryNameAsync();
        }
        
        public string getCategoryId(string categoryName) {
            return base.Channel.getCategoryId(categoryName);
        }
        
        public System.Threading.Tasks.Task<string> getCategoryIdAsync(string categoryName) {
            return base.Channel.getCategoryIdAsync(categoryName);
        }
        
        public string insertProduct(string productId, string ProductName, string categoryId, int price, int qty) {
            return base.Channel.insertProduct(productId, ProductName, categoryId, price, qty);
        }
        
        public System.Threading.Tasks.Task<string> insertProductAsync(string productId, string ProductName, string categoryId, int price, int qty) {
            return base.Channel.insertProductAsync(productId, ProductName, categoryId, price, qty);
        }
        
        public System.Data.DataSet SearchProdcut(string productId) {
            return base.Channel.SearchProdcut(productId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SearchProdcutAsync(string productId) {
            return base.Channel.SearchProdcutAsync(productId);
        }
        
        public System.Data.DataSet DisplayProduct1() {
            return base.Channel.DisplayProduct1();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DisplayProduct1Async() {
            return base.Channel.DisplayProduct1Async();
        }
        
        public string UpdateProduct(string productId1, string ProductName, string categoryId, int price, int qty) {
            return base.Channel.UpdateProduct(productId1, ProductName, categoryId, price, qty);
        }
        
        public System.Threading.Tasks.Task<string> UpdateProductAsync(string productId1, string ProductName, string categoryId, int price, int qty) {
            return base.Channel.UpdateProductAsync(productId1, ProductName, categoryId, price, qty);
        }
        
        public string DeleteProduct(string ProductId) {
            return base.Channel.DeleteProduct(ProductId);
        }
        
        public System.Threading.Tasks.Task<string> DeleteProductAsync(string ProductId) {
            return base.Channel.DeleteProductAsync(ProductId);
        }
        
        public int AddStock(string productId, int newStock) {
            return base.Channel.AddStock(productId, newStock);
        }
        
        public System.Threading.Tasks.Task<int> AddStockAsync(string productId, int newStock) {
            return base.Channel.AddStockAsync(productId, newStock);
        }
    }
}
