//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerClient_WebApplication.CategoryServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CategoryServiceReference.CategoryWebServiceSoap")]
    public interface CategoryWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoCategoryId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AutoCategoryId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoCategoryId", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AutoCategoryIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertCategory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string insertCategory(string CategoryId, string CategoryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<string> insertCategoryAsync(string CategoryId, string CategoryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DisplayCategory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DisplayCategory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DisplayCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> DisplayCategoryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCategory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateCategory(string categoryId, string categoryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdateCategoryAsync(string categoryId, string categoryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCategory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DeleteCategory(string categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DeleteCategoryAsync(string categoryId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CategoryWebServiceSoapChannel : CustomerClient_WebApplication.CategoryServiceReference.CategoryWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CategoryWebServiceSoapClient : System.ServiceModel.ClientBase<CustomerClient_WebApplication.CategoryServiceReference.CategoryWebServiceSoap>, CustomerClient_WebApplication.CategoryServiceReference.CategoryWebServiceSoap {
        
        public CategoryWebServiceSoapClient() {
        }
        
        public CategoryWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CategoryWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoryWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoryWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AutoCategoryId() {
            return base.Channel.AutoCategoryId();
        }
        
        public System.Threading.Tasks.Task<string> AutoCategoryIdAsync() {
            return base.Channel.AutoCategoryIdAsync();
        }
        
        public string insertCategory(string CategoryId, string CategoryName) {
            return base.Channel.insertCategory(CategoryId, CategoryName);
        }
        
        public System.Threading.Tasks.Task<string> insertCategoryAsync(string CategoryId, string CategoryName) {
            return base.Channel.insertCategoryAsync(CategoryId, CategoryName);
        }
        
        public System.Data.DataSet DisplayCategory() {
            return base.Channel.DisplayCategory();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DisplayCategoryAsync() {
            return base.Channel.DisplayCategoryAsync();
        }
        
        public string UpdateCategory(string categoryId, string categoryName) {
            return base.Channel.UpdateCategory(categoryId, categoryName);
        }
        
        public System.Threading.Tasks.Task<string> UpdateCategoryAsync(string categoryId, string categoryName) {
            return base.Channel.UpdateCategoryAsync(categoryId, categoryName);
        }
        
        public string DeleteCategory(string categoryId) {
            return base.Channel.DeleteCategory(categoryId);
        }
        
        public System.Threading.Tasks.Task<string> DeleteCategoryAsync(string categoryId) {
            return base.Channel.DeleteCategoryAsync(categoryId);
        }
    }
}
